name: Continuous Integration Quality Check

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set OpenAI API Key
        run: echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> $GITHUB_ENV
      - name: Install build dependencies
        run: sudo apt-get install -y portaudio19-dev
      - name: Install dependencies
        run: make install
      - name: lint
        run: make lint
      - name: test
        run: make test
      - name: format
        run: make format

